services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 2003
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  # Expose container port to host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_net

volumes:
  postgres_data:

networks:
  postgres_net: